function o = FilterInstData(o, params)

%
% function o = FilterInstrumentData(o, params)
%
% Paul SanGiorgio 6 July 2015
%
% This function applies a simple rolling average filter to all of the
% instrument data (i.e. metadata).  The number of points in the rolling
% average is determined by the parameter structure.  If no params structure
% is given, it reverts to default values hard-coded in here.
%
%
% params structure:
%
% the params structure has the following fields
%
% params.(instDataName).navg - the number of points to rolling average
% together
% params.(instDataName).loc - the location of the instrument data specified
% by instDataName, referenced to the root of the DataWrapper (i.e. o)
% object.

% this is the list of instDataNames that get filtered.  Most of them are
% filtered with a default value of "1" point, i.e. no filtering.

if nargin < 2
    params = struct();
end

fieldList= {'ChipTempIPTAT','ChipTempRTDU','ChipTempRTDM','ChipTempRTDL',...
    'SysTempCuBlock','SysTempHeatSink','SysTempPreheater','SysTempAmbient',...
    'SysTempVref','PeltierPIDEffort','PreheaterPIDEffort',...
    'ChipVoltageADCVref','ChipVoltageAFEVref','ChipVoltageRFVHi',...
    'ChipVoltageRFVLo','ChipVoltagePPoly','ChipVoltageRFVHiNB','ChipVOltageRFVLoNB',...
    'Flowrate','Flowrate2','SysPressurePump','SysPressureCartridge',...
    'CartridgePIDEffort','DVDD12','DVDD33','AVDD33','DVDD12Current',...
    'DVDD33Current','AVDD33Current'};

nf = numel(fieldList);

for kf = 1:nf
    % set up default values
    if ~isfield(params,fieldList{kf})
        params.(fieldList{kf}) = getDefault(fieldList{kf});
    end
    loc = params.(fieldList{kf}).loc;
    loc_raw = loc;
    loc_raw{end} = [loc{end} '_raw'];
    o = setfield(o,loc_raw{:},getfield(o,loc{:}));
    o = setfield(o,loc{:},rollAvg(getfield(o,loc{:}),params.(fieldList{kf}).navg));
end

function yOut = rollAvg(yIn,navg)

% I copied this from the matlab documentation of the built-in filter
% function
b = (1./navg).*ones(1,navg);
yOut = filter(b,1,yIn);


function structOut = getDefault(fieldName)

defaultVals = {{'ChipTempIPTAT',1,'ChipTemp','Readout','IPTAT'},...
    {'ChipTempRTDU',1,'ChipTemp','Readout','RTDU'},...
    {'ChipTempRTDM',1,'ChipTemp','Readout','RTDM'},...
    {'ChipTempRTDL',1,'ChipTemp','Readout','RTDL'},...
    {'SysTempCuBlock',1,'SysTemp','Readout','CuBlock'},...
    {'SysTempHeatSink',1,'SysTemp','Readout','HeatSink'},...
    {'SysTempPreheater',1,'SysTemp','Readout','Preheater'},...
    {'SysTempAmbient',1,'SysTemp','Readout','Ambient'},...
    {'SysTempVref',1,'SysTemp','Readout','Vref'},...
    {'CartridgePIDEffort',1,'ValveState','CartridgePIDEffort'},...
    {'PeltierPIDEffort',1,'ValveState','PeltierPIDEffort'},...
    {'PreheaterPIDEffort',1,'ValveState','PreheaterPIDEffort'},...
    {'ChipVoltageADCVref',1,'ChipVoltage','Readout','ADCVref'},...
    {'ChipVoltageAFEVref',1,'ChipVoltage','Readout','AFEVref'},...
    {'ChipVoltageRFVHi',1,'ChipVoltage','Readout','RFVHi'},...
    {'ChipVoltageRFVLo',1,'ChipVoltage','Readout','RFVLo'},...
    {'ChipVoltagePPoly',1,'ChipVoltage','Readout','PPoly'},...
    {'ChipVoltageRFVHiNB',1,'ChipVoltage','Readout','RFVHiNB'},...
    {'ChipVOltageRFVLoNB',1,'ChipVoltage','Readout','RFVLoNB'},...
    {'Flowrate',1,'FlowSensor','Readout'},...
    {'Flowrate2',1,'FlowSensor','Readout2'},...
    {'Flowrate3',1,'FlowSensor','Readout3'},...
    {'SysPressurePump',1,'SysPressure','Readout','Pump'},...
    {'SysPressureCartridge',50,'SysPressure','Readout','Cartridge'},...
    {'DVDD12',1,'SysVoltage','DVDD12'},...
    {'DVDD33',1,'SysVoltage','DVDD33'},...
    {'AVDD33',1,'SysVoltage','AVDD33'},...
    {'DVDD12Current',100,'SysVoltage','DVDD12current'},...
    {'DVDD33Current',100,'SysVoltage','DVDD33current'},...
    {'AVDD33Current',100,'SysVoltage','AVDD33current'}};

found = false;

for k = 1:numel(defaultVals)
    if strcmp(fieldName,defaultVals{k}{1})
        structOut.navg = defaultVals{k}{2};
        structOut.loc = defaultVals{k}(3:end);
        found = true;
        break
    end
end

if ~found
    structOut.navg = 1;
    structOut.loc = {''};
end